#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

pnpm run build

if [[ $(git diff --cached --name-only | grep dist) ]]; then
  echo "dist folder is in git changes"
  exit 0
else
  echo "dist folder is not in git changes"
  exit 1
fi

exit 1